version: "3.9"

services:
    postgres:
        container_name: postgres
        image: postgres:13.2-alpine
        restart: always
        networks:
            postgres:
                ipv4_address: 10.20.16.2
        # ports:
        #   - 5432:5432
        environment:
            POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        networks:
            postgres:
                ipv4_address: 10.20.16.3
        environment:
            PGADMIN_DEFAULT_EMAIL: executor55@gmx.de
            PGADMIN_DEFAULT_PASSWORD: <PGADMIN_DEFAULT_PASSWORD>
            PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            - pgadmin-certs:/certs
    adminer:
        container_name: adminer
        image: adminer:latest
        restart: unless-stopped
        networks:
            postgres:
                ipv4_address: 10.20.16.4
        # ports:
        #   - 8080:8080

networks:
    postgres:
        name: postgres
        ipam:
            driver: default
            config:
                - subnet: "10.20.16.0/20"
                  gateway: 10.20.16.1

volumes:
    postgres-data:
        name: postgres-data
    pgadmin-data:
        name: pgadmin-data
    pgadmin-certs:
        name: pgadmin-certs
