version: "3.9"

services:
  # https://hub.docker.com/r/klutchell/unbound
    unbound:
        container_name: unbound
        cap_add:
            - NET_ADMIN
            - CAP_NET_BIND_SERVICE
            - CAP_NET_RAW
            - CAP_NET_ADMIN
        image: klutchell/unbound:latest
        restart: unless-stopped
        ports:
            - "53:5053/tcp"
            - "53:5053/udp"
        networks:
            pihole:
                ipv4_address: 10.20.208.2
                ipv6_address: fd4d:10:20:208::2
                aliases:
                    - unbound
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        volumes:
            - unbound-conf:/etc/unbound
        healthcheck:
            test: [ "CMD", "drill", "-Qp", "53", "nlnetlabs.nl", "@127.0.0.1" ]
            interval: "30s"
            timeout: "30s"
            retries: "3"
            start_period: "5s"

  # https://hub.docker.com/r/pihole/pihole
    pihole:
        container_name: pihole
      # cap_add:
      #     - NET_ADMIN
      #     - CAP_NET_BIND_SERVICE
      #     - CAP_NET_RAW
      #     - CAP_NET_ADMIN
        image: jacklul/pihole:latest    # extension from pihole/pihole:latest
        restart: unless-stopped
        networks:
            pihole:
                ipv4_address: 10.20.208.3
                ipv6_address: fd4d:10:20:208::3
                aliases:
                    - pihole
        ports:
          # - "53:53/tcp"
          # - "53:53/udp"
          # - "67:67/udp"
            - "2213:80/tcp"
          # - "443:443/tcp"
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            TZ: "Europe/Berlin"
            ADMIN_EMAIL: "executor55@gmx.de"
            WEBPASSWORD: '<WEBPASSWORD>'
            ServerIP: "11.22.33.44"
            ServerIPv6: "2003:abcd:1234:567::1"                 # If you have a v6 network set to your server's LAN IPv6 to block IPv6 ads fully
            PIHOLE_DNS_: "10.20.208.2#5053" # Upstream DNS server(s) for Pi-hole
            PIHOLE_DOMAIN: "3x3cut0r.de"    # Domain name sent by the DHCP server.
            VIRTUAL_HOST: "https://pihole.3x3cut0r.de"          # What your web server 'virtual host' is, accessing admin through this Hostname/IP allows you to make changes to the whitelist / blacklists in addition to the default 'http://pi.hole/admin/' address
            DNSSEC: "true"                  # Enable DNSSEC support
            DNS_BOGUS_PRIV: "true"          # Enable forwarding of reverse lookups for private ranges
            DNS_FQDN_REQUIRED: "true"       # Never forward non-FQDNs
            REV_SERVER: "false"             # Enable DNS conditional forwarding for device name resolution
            REV_SERVER_DOMAIN: ""           # If conditional forwarding is enabled, set the domain of the local network router
            REV_SERVER_TARGET: ""           # If conditional forwarding is enabled, set the IP of the local network router
            REV_SERVER_CIDR: ""             # If conditional forwarding is enabled, set the reverse DNS zone (e.g. 192.168.0.0/24)
            DHCP_ACTIVE: "false"            # Enable DHCP server. Static DHCP leases can be configured with a custom /etc/dnsmasq.d/04-pihole-static-dhcp.conf
            DHCP_START: ""                  # Start of the range of IP addresses to hand out by the DHCP server (mandatory if DHCP server is enabled).
            DHCP_END: ""                    # End of the range of IP addresses to hand out by the DHCP server (mandatory if DHCP server is enabled).
            DHCP_ROUTER: ""                 # Router (gateway) IP address sent by the DHCP server (mandatory if DHCP server is enabled).
            DHCP_LEASETIME: "24"            # DHCP lease time in hours.
            DHCP_IPv6: "false"              # Enable DHCP server IPv6 support (SLAAC + RA).
            DHCP_rapid_commit: "false"      # Enable DHCPv4 rapid commit (fast address assignment).
            IPv6:: "true"                   # For unraid compatibility, strips out all the IPv6 configuration from DNS/Web services when false.
            TEMPERATUREUNIT: "c"            # Set preferred temperature unit to c: Celsius, k: Kelvin, or f Fahrenheit units.
            WEBUIBOXEDLAYOUT: "boxed"       # Use boxed layout (helpful when working on large screens) <boxed|traditional>
            QUERY_LOGGING: "true"           # Enable query logging or not.
            INTERFACE: "eth0"               # The default works fine with our basic example docker run commands. If you're trying to use DHCP with --net host mode then you may have to customize this or DNSMASQ_LISTENING.
            DNSMASQ_LISTENING: "all"        # local listens on all local subnets, all permits listening on internet origin subnets in addition to local, single listens only on the interface specified. <local|all|single>
          # WEB_PORT: ""                    # This will break the 'webpage blocked' functionality of Pi-hole however it may help advanced setups like those running synology or --net=host docker argument. This guide explains how to restore webpage blocked functionality using a linux router DNAT rule: Alternative Synology installation method
          # SKIPGRAVITYONBOOT: ""           # Use this option to skip updating the Gravity Database when booting up the container. By default this environment variable is not set so the Gravity Database will be updated when the container starts up. Setting this environment variable to 1 (or anything) will cause the Gravity Database to not be updated when container starts up. <unset|1>
        volumes:
            - pihole-data:/etc/pihole/
            - pihole-dnsmasq.d:/etc/dnsmasq.d/
            - /home/docker/config-files/pihole/pihole-updatelists:/etc/pihole-updatelists/
        depends_on:
            - unbound

networks:
    pihole:
        name: pihole
        ipam:
            driver: default
            config:
                - subnet: "10.20.208.0/20"
                  gateway: 10.20.208.1
                - subnet: "fd4d:10:20:208::/64"
                  gateway: fd4d:10:20:208::1
  # nginx:
  #     external:
  #         name: nginx

volumes:
    pihole-data:
        name: pihole-data
    pihole-dnsmasq.d:
        name: pihole-dnsmasq.d
    pihole-updatelists:
        name: pihole-updatelists
    unbound-conf:
        name: unbound-conf
