version: '3.9'

services:
  # https://hub.docker.com/r/3x3cut0r/filesender
  filesender:
    container_name: filesender
    image: 3x3cut0r/filesender:latest
    restart: unless-stopped
    networks:
      filesender:
        ipv4_address: '10.24.16.2'
      mariadb:
        ipv4_address: '10.20.0.116'
    ports:
      - '2116:80'
    # - "9116:9000"
    dns:
      - '1.1.1.1'
      - '1.0.0.1'
      - '2606:4700:4700::1111'
      - '2606:4700:4700::1001'
    environment:
      FILESENDER_URL: 'https://filesender.3x3cut0r.de'
      FILESENDER_TRUSTED_DOMAINS: 'filesender.3x3cut0r.de'
      SIMPLESAML_LANGUAGE_DEFAULT: 'de'
      ADMIN_EMAIL: 'executor55@gmx.de'
      ADMIN_USER: '3x3cut0r'
      ADMIN_PASSWORD: '<ADMIN_PASSWORD>'
      DB_TYPE: 'mysql'
      DB_HOST: 'mariadb'
      DB_NAME: 'filesender'
      DB_PORT: '3306'
      DB_USER: 'filesender'
      DB_PASSWORD: '<DB_PASSWORD>'
      TZ: 'Europe/Berlin'
    volumes:
      - filesender-conf:/config
      - filesender-data:/data

networks:
  filesender:
    name: filesender
    ipam:
      driver: default
      config:
        - subnet: '10.24.16.0/24'
          gateway: '10.24.16.1'
  mariadb:
    name: mariadb
    external: true

volumes:
  filesender-conf:
    name: filesender-conf
  filesender-data:
    name: filesender-data
