version: '3.9'

# https://github.com/crowdsecurity/crowdsec
services:
  # https://hub.docker.com/r/crowdsecurity/crowdsec
  crowdsec-agent:
    container_name: crowdsec-agent
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      crowdsec:
        ipv4_address: '10.10.0.3'
    dns:
      - '1.1.1.1'
      - '1.0.0.1'
      - '2606:4700:4700::1111'
      - '2606:4700:4700::1001'
    environment:
      TZ: 'Europe/Berlin'
      DISABLE_LOCAL_API: true
      AGENT_USERNAME: 'crowdsec' # agent_user_name previously registered with LAPI
      AGENT_PASSWORD: '<AGENT_PASSWORD>' # agent_password previously registered with LAPI
      LOCAL_API_URL: 'http://crowdsec:8080'
    volumes:
      - crowdsec-conf:/etc/crowdsec
      - crowdsec-data:/var/lib/crowdsec/data

networks:
  crowdsec:
    name: crowdsec
    ipam:
      driver: default
      config:
        - subnet: '10.10.0.0/24'
          gateway: '10.10.0.1'

volumes:
  crowdsec-conf:
    name: crowdsec-conf
  crowdsec-data:
    name: crowdsec-data
