version: "3.9"

services:
  # https://hub.docker.com/r/donch/net-tools
    net-tools:
        container_name: net-tools
        hostname: net-tools
        image: donch/net-tools:latest
        restart: "no"
        networks:
            net-tools:
                ipv4_address: 10.255.255.2

networks:
    net-tools:
        name: net-tools
        ipam:
            driver: default
            config:
                - subnet: "10.255.255.0/24"
                  gateway: 10.255.255.1
