version: "3.9"

# https://github.com/coturn/coturn
services:
  # https://hub.docker.com/r/coturn/coturn
    coturn:
        container_name: coturn
        image: coturn/coturn:latest
        restart: unless-stopped
        command: -c /etc/coturn/turnserver.conf
      # network_mode: host # for docker rootful only!
        ports:
          # - "2214:8080" # web-admin
            - "3478:3478"
            - "3478:3478/udp"
            - "5349:5349" # tls-listening-port
            - "5349:5349/udp" # tls-listening-port
            - "49152-49200:49152-49200/udp" # too many ports kills docker rootless. rootful docker with network=host is recommended!
        networks:
            coturn:
                ipv4_address: 10.20.224.2
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            TZ: "Europe/Berlin"
        volumes:
            - /home/docker/config-files/coturn/turnserver.conf:/etc/coturn/turnserver.conf
            - /home/docker/config-files/coturn/turn_server_cert.pem:/etc/coturn/turn_server_cert.pem
            - /home/docker/config-files/coturn/turn_server_pkey.pem:/etc/coturn/turn_server_pkey.pem
            - /home/docker/config-files/coturn/turn_server_dhparam.pem:/etc/coturn/turn_server_dhparam.pem
            - coturn-data:/var/lib/coturn

networks:
    coturn:
        name: coturn
        ipam:
            driver: default
            config:
                - subnet: "10.20.224.0/24"
                  gateway: 10.20.224.1

volumes:
    coturn-data:
        name: coturn-data