version: "3.9"

# https://github.com/linuxserver/docker-webtop
services:
  # https://hub.docker.com/r/linuxserver/webtop
    webtop:
        container_name: webtop
        image: lscr.io/linuxserver/webtop:latest
        shm_size: 2gb
        restart: unless-stopped
        security_opt:
            - seccomp:unconfined        #optional
        ports:
            - "80:3000"
        networks:
            webtop:
                ipv4_address: 10.24.22.2
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            TZ: "Europe/Berlin"
          # PUID: "1000"
          # PGID: "1000"
          # SUBFOLDER: "/"              #optional
            KEYBOARD: "en-us-qwerty"    #optional
        volumes:
            - webtop-conf:/config
          # - /run/user/1000/docker.sock:/var/run/docker.sock   #optional

networks:
    webtop:
        name: webtop
        ipam:
            driver: default
            config:
                - subnet: "10.24.22.0/24"
                  gateway: 10.24.22.1

volumes:
    webtop-conf:
        name: webtop-conf
