version: '3.9'

services:
  api:
    environment:
      HOST: localhost
      PORT: 3080
      MONGO_URI: 'mongodb://127.0.0.1:27017/LibreChat'
      DOMAIN_CLIENT: 'http://localhost:3080'
      DOMAIN_SERVER: 'http://localhost:3080'
      UID: 1000
      GID: 1000
      APP_TITLE: 'LibreChat'
      CONFIG_PATH: '/app/librechat.yaml'
      SEARCH: true
      MEILI_NO_ANALYTICS: true
      MEILI_HOST: 'http://0.0.0.0:7700'
      MEILI_MASTER_KEY: '<MEILI_MASTER_KEY>'
      ANTHROPIC_API_KEY: 'user_provided'
      BINGAI_TOKEN: 'user_provided'
      GOOGLE_KEY: 'user_provided'
      OPENAI_API_KEY: 'user_provided'
      # OPENAI_REVERSE_PROXY: 'http://litellm:8000/v1/chat/completions'
      MISTRAL_API_KEY: 'user_provided'
      OPENROUTER_KEY: 'user_provided'
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.6.2
    environment:
      MEILI_MASTER_KEY: 'MASTER_KEY'
