version: "3.9"

services:
  # https://hub.docker.com/r/jlesage/firefox
    firefox:
        container_name: firefox
        image: jlesage/firefox:latest
        shm_size: 2gb
        restart: always
        networks:
            firefox:
                ipv4_address: 10.24.4.2
            nginx:
                ipv4_address: 10.24.0.104
        # ports:
        #   - 5800:5800
        #   - 5800:5800
        environment:
            TZ: Europe/Berlin
            VNC_PASSWORD: <VNC_PASSWORD>
            USER_ID: "1000"
            GROUP_ID: "1000"
            KEEP_APP_RUNNING: "1"
            DISPLAY_WIDTH: "1280"
            DISPLAY_HEIGHT: "800"
            CLEAN_TMP_DIR: "1"
        volumes:
            - firefox-data:/config

networks:
    firefox:
        name: firefox
        ipam:
            driver: default
            config:
                - subnet: "10.24.4.0/24"
                  gateway: 10.24.4.1
    nginx:
        external:
            name: nginx

volumes:
    firefox-data:
        name: firefox-data
