version: "3.9"

services:
  # https://hub.docker.com/r/portainer/portainer-ce
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:alpine
        restart: always
        env_file: ../../env-files/portainer.env
        networks:
            portainer:
                ipv4_address: 10.24.1.2
            traefik:
                ipv4_address: 10.10.24.1
        ports:
          # - 8000:8000
            - 2101:9000
        environment:
            COMPOSE_HTTP_TIMEOUT: 240
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        volumes:
            - /run/user/1000/docker.sock:/var/run/docker.sock
            - portainer-data:/data
        labels:
          # Frontend
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`portainer.3x3cut0r.de`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.services.frontend.loadbalancer.server.port=2101"
            - "traefik.http.routers.frontend.service=frontend"
            - "traefik.http.routers.frontend.tls.certresolver=leresolver"
          # Edge
          # - "traefik.http.routers.edge.rule=Host(`edge.3x3cut0r.de`)"
          # - "traefik.http.routers.edge.entrypoints=websecure"
          # - "traefik.http.services.edge.loadbalancer.server.port=8000"
          # - "traefik.http.routers.edge.service=edge"
          # - "traefik.http.routers.edge.tls.certresolver=leresolver"

networks:
    portainer:
        name: portainer
        ipam:
            driver: default
            config:
                - subnet: "10.24.1.0/24"
                  gateway: 10.24.1.1
    traefik:
        external:
            name: traefik

volumes:
    portainer-data:
        name: portainer-data
