version: "3.9"

# https://github.com/parse-community/parse-server
services:
  # https://hub.docker.com/r/bitnami/parse
    parse-server:
        container_name: parse-server
        image: bitnami/parse:5
        restart: unless-stopped
        ports:
            - "1337:1337"
        networks:
            parse:
                ipv4_address: 10.24.37.2
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
<<<<<<< HEAD
            PARSE_ENABLE_HTTPS: 'no'
            PARSE_BIND_HOST: 'parse-server'
            PARSE_HOST: 'parse-server'
            PARSE_PORT_NUMBER: '1337'
            PARSE_APP_ID: '<PARSE_APP_ID>'
            PARSE_MASTER_KEY: '<PARSE_MASTER_KEY>'
            PARSE_APP_NAME: '<PARSE_APP_NAME>'
            PARSE_MOUNT_PATH: '/parse'
            PARSE_ENABLE_CLOUD_CODE: 'no'
            PARSE_DATABASE_HOST: 'parse-mongo'
            PARSE_DATABASE_PORT_NUMBER: '27017'
            PARSE_DATABASE_USER: 'parse'
            PARSE_DATABASE_NAME: 'parse'
            PARSE_DATABASE_PASSWORD: '<MONGODB_PASSWORD>'
=======
            PARSE_SERVER_APPLICATION_ID: '<PARSE_SERVER_APPLICATION_ID>'
            PARSE_SERVER_MASTER_KEY: '<PARSE_SERVER_MASTER_KEY>'
            PARSE_SERVER_DATABASE_URI: 'mongodb://admin:<MONGO_INITDB_ROOT_PASSWORD>@parse-mongo/parse_server?authSource=admin'
            PARSE_ENABLE_CLOUD_CODE: 'no'
          # PARSE_SERVER_CLOUD: '/parse-server/cloud/main.js'
          # PARSE_SERVER_PUSH: '{"ios":{"pfx":"/parse-server/pushcert/prod.p12","topic":"com.domain.Parse-1","production":false}}'
          # PARSE_SERVER_LOG_LEVEL: 'error'
            VERBOSE: 1
>>>>>>> a8d8bf82d273de30823d1be508360cf483a033b7
        volumes:
            - parse-server-conf:/bitnami/parse
        depends_on:
            - parse-mongo

  # https://hub.docker.com/r/bitnami/parse-dashboard
    parse-dashboard:
        container_name: parse-dashboard
        image: bitnami/parse-dashboard:latest
        restart: unless-stopped
        command: 'parse-dashboard --dev'
        ports:
            - "4040:4040"
        networks:
            parse:
                ipv4_address: 10.24.37.3
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
<<<<<<< HEAD
            PARSE_DASHBOARD_ENABLE_HTTPS: 'no'
            PARSE_DASHBOARD_EXTERNAL_HTTP_PORT_NUMBER: '80'
            PARSE_DASHBOARD_EXTERNAL_HTTPS_PORT_NUMBER: '80'
            PARSE_DASHBOARD_PARSE_HOST: 'parse-server'
            PARSE_DASHBOARD_PORT_NUMBER: '4040'
            PARSE_DASHBOARD_PARSE_PORT_NUMBER: '1337'
            PARSE_DASHBOARD_PARSE_APP_ID: '<PARSE_APP_ID>'
            PARSE_DASHBOARD_PARSE_APP_NAME: '<PARSE_APP_NAME>'
            PARSE_DASHBOARD_PARSE_MASTER_KEY: '<PARSE_MASTER_KEY>'
            PARSE_DASHBOARD_PARSE_MOUNT_PATH: '/parse'
            PARSE_DASHBOARD_PARSE_PROTOCOL: 'http'
            PARSE_DASHBOARD_USERNAME: 'admin'
            PARSE_DASHBOARD_PASSWORD: '<PARSE_PASSWORD>'
=======
            PARSE_DASHBOARD_APP_ID: '<PARSE_SERVER_APPLICATION_ID>'
            PARSE_DASHBOARD_MASTER_KEY: '<PARSE_SERVER_MASTER_KEY>'
            PARSE_DASHBOARD_USER_ID: 'admin'
            PARSE_DASHBOARD_USER_PASSWORD: '<MONGO_INITDB_ROOT_PASSWORD>'
          # PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 'true'
            PARSE_DASHBOARD_TRUST_PROXY: 1
            PARSE_DASHBOARD_COOKIE_SESSION_SECRET: '<PARSE_SERVER_COOKIE_SESSION_SECRET>'
          # PARSE_DASHBOARD_SERVER_URL: 'http://parse-server:1337/parse'
          # MOUNT_PATH: '/parse'
>>>>>>> a8d8bf82d273de30823d1be508360cf483a033b7
        volumes:
            - parse-dashboard-conf:/bitnami
        depends_on:
            - parse-server

  # https://hub.docker.com/r/bitnami/mongodb
    parse-mongo:
        container_name: parse-mongo
        image: bitnami/mongodb:5.0
        restart: unless-stopped
        networks:
            parse:
                ipv4_address: 10.24.37.4
      # ports:
      #     - 27017:27017
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
            MONGODB_DATABASE: 'parse'
            MONGODB_USERNAME: 'parse'
            MONGODB_PASSWORD: '<MONGODB_PASSWORD>'
        volumes:
            - parse-mongo-data:/bitnami/mongodb

networks:
    parse:
        name: parse
        ipam:
            driver: default
            config:
                - subnet: "10.24.37.0/24"
                  gateway: 10.24.37.1

volumes:
    parse-server-conf:
        name: parse-server-conf
    parse-dashboard-conf:
        name: parse-dashboard-conf
    parse-mongo-data:
        name: parse-mongo-data
