max_procs: 1

filebeat.inputs:
  - type: filestream
    paths:
      - /var/lib/docker/containers/*/*.log
    include_files: ['.*\.log']
    exclude_files: ['.*\.gz$']
    parsers:
      - ndjson:
          keys_under_root: true
          message_key: log
          ignore_decoding_error: true
    processors:
      - decode_json_fields:
          fields: ['message']
          target: ''
          overwrite_keys: false
      - add_docker_metadata: ~
      - drop_fields:
          fields: ['agent', 'ecs', 'log']

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.logstash:
  hosts: ["logstash:5044"]
  username: "filebeat"
  password: "<PASSWORD>"

setup.kibana:
  host: "kibana:5601"

setup.ilm.enabled: true
setup.ilm.policy_name: "30_days_deletion_policy"
setup.template.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.fields: "fields.yml"
setup.template.overwrite: true
