version: "3.9"

services:
  # https://hub.docker.com/_/nginx
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 2100:80
          # - 4100:443
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        volumes:
            - nginx-html:/var/www/html
            - nginx-conf.d:/etc/nginx/conf.d
          # - certbot-letsencrypt:/etc/nginx/ssl
        depends_on:
            - php-fpm

  # https://hub.docker.com/_/php
    php-fpm:
        container_name: php-fpm
        image: php:8-fpm-alpine
        restart: always
        networks:
            nginx:
                ipv4_address: 10.24.0.3
        ports:
           - 9000:9000
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        volumes:
            - nginx-html:/var/www/html

networks:
    nginx:
      name: nginx
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 10.24.0.0/24
                gateway: 10.24.0.1

volumes:
    nginx-html:
        name: nginx-html
    nginx-conf.d:
        name: nginx-conf.d
  # certbot-letsencrypt:
  #     name: certbot-letsencrypt
