version: "3.9"

services:
  # https://hub.docker.com/_/nginx
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        networks:
            nginx:
                ipv4_address: 10.24.0.2
        ports:
            - 80:80
            - 443:443
        volumes:
            - nginx-html:/var/www/html
            - nginx-conf.d:/etc/nginx/conf.d
            - certbot-letsencrypt:/etc/nginx/ssl

  # https://hub.docker.com/_/php
    php-fpm:
        container_name: php-fpm
        image: php:8-fpm-alpine
        networks:
            nginx:
                ipv4_address: 10.24.0.3
        # ports:
        #    - 9000:9000
        volumes:
            - nginx-html:/var/www/html

networks:
    nginx:
      name: nginx
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 10.24.0.0/24
                gateway: 10.24.0.1

volumes:
    nginx-html:
        name: nginx-html
    nginx-conf.d:
        name: nginx-conf.d
    certbot-letsencrypt:
        name: certbot-letsencrypt
