#!/bin/sh
LOGFILE="/var/log/ifup-vmbr40.log"
echo "$(date) if-up.d/vmbr40 called for IFACE=$IFACE" >> "$LOGFILE"

[ "$IFACE" = "vmbr40" ] || exit 0

echo "$(date) running /opt/scripts/network/post-up.sh" >> "$LOGFILE"
/opt/scripts/network/post-up.sh >> "$LOGFILE" 2>&1
echo "$(date) done" >> "$LOGFILE"
