version: '3.9'

# https://github.com/docker/mcp-gateway
services:
  # https://hub.docker.com/r/docker/mcp-gateway
  mcp-gateway:
    container_name: mcp-gateway
    image: app/image:tag
    restart: unless-stopped
    command: ['--port=8080', '--transport=streaming']
    ports:
      - '2143:8080'
    networks:
      mcp-gateway:
        ipv4_address: '10.24.43.2'
    dns:
      - '1.1.1.1'
      - '1.0.0.1'
      - '2606:4700:4700::1111'
      - '2606:4700:4700::1001'
    volumes:
      - /root/.docker/mcp:/root/.docker/mcp # config/secrets
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  mcp-gateway:
    name: mcp-gateway
    ipam:
      driver: default
      config:
        - subnet: '10.24.43.0/24'
          gateway: '10.24.43.1'
